<<<<<<< HEAD
# Generated by Django 5.1 on 2024-09-07 01:50
=======
 django-admin
# Generated by Django 5.1 on 2024-09-04 23:45
=======
 Post
# Generated by Django 5.1 on 2024-08-31 13:42
 main
>>>>>>> 5423a4d12a02f3b4973107cd4a4dcb756dcb7491

=======
import django.db.models.deletion
from django.conf import settings
 main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
 Post
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 main
    ]

    operations = [
        migrations.CreateModel(
 django-admin
            name='Post',
=======
 Post
            name='BlogPost',
 main
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
=======
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
 main
        ),
    ]
