<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.1 on 2024-08-15 22:48
=======
# Generated by Django 5.1 on 2024-08-18 13:31
>>>>>>> be7be5a (fix)

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1 on 2024-08-18 13:31

>>>>>>> be7be5acd831662d9d1223c4805a8cdbba7ebed8
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> be7be5acd831662d9d1223c4805a8cdbba7ebed8
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
=======
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
>>>>>>> be7be5acd831662d9d1223c4805a8cdbba7ebed8
        ),
    ]
