# Generated by Django 5.1 on 2024-08-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_blogpost'),
    ]

    #operations = [
      #  migrations.RemoveField(
      #      model_name='blogpost',
      #    name='published_date',
      #),
    #]
