# Generated by Django 5.1 on 2024-08-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_published_date'),
    ]